### ISSUE TITLE
docker push 시 denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by jaehui327** [sangyeol-kim/ausg-docker-seminar#10]
계정과 연결하려면, 
이미지 이름에
Docker Hub 계정 이름(Docker Hub의 네임스페이스)을 포함해야 합니당

그렇지 않았을 경우 docker login 해도 레포로 푸시가 되지 않습니다.

해결방법은 

1. 이미지명 앞에 Docker Hub 계정을 붙여서 
(Docker Hub 계정)/docker-repo:first-image 와 같이 새로 만들어줍니다.

2. tag를 변경해줍니다.
$ docker tag first-image (Docker Hub 계정)/docker-repo:first-image
$ docker push (Docker Hub 계정)/docker-repo:first-image

참고 링크 : https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker

**Comment by socar-salt** [comment]
이글을 읽고 암이 나았습니다.

**Comment by charbori** [comment]
많은 도움이 되었습니다. 감사합니다~

**Comment by mrbluesky0123** [comment]
이 글을 읽고 암이 나았습니다222222222222

**Comment by jeonhyoseung** [comment]
이 글을 읽고 암이 나았습니다 333333333333333
