### ISSUE TITLE
Docker 시작

### ISSUE THREAD

**Issue by yebonkim** [sangyeol-kim/ausg-docker-seminar#2]
테스팅 환경 : MAC

docker 본격적인 시작 전에 docker Application이 실행되어있지 않으면

docker: Cannot connect to the Docker Daemon at.... 이라는 오류가 납니다.

시작전에 docker application 켜달라고 써있으면 좋을 것 같습니다.ㅎㅎ

**Comment by sangyeol-kim** [comment]
네! 그리고 밋업 공지를 확인해봤는데 Mac 환경에서 설치할 때 brew로 설치하는 것은 클라이언트 환경을 구축하는 것이고 서버를 돌리기 위해서는 추가적으로 애플리케이션 설치가 필요합니다! 애플리케이션 설치가 선택 사항처럼 되어 있어서 밋업 수정해주시면 감사하겠습니다 :)
