### ISSUE TITLE
5번 부분 실습 중 건의내용

### ISSUE THREAD

**Issue by yebonkim** [sangyeol-kim/ausg-docker-seminar#5]
5.3 이후에 exit 명령어를 추가하여 우분투 환경에서 나와야 한다는 것을 추가해주시면 더 쉽게 따라올 수 있을 것 같습니다!

이후 docker commit 이전에

이미지 이름과 태그 이름을 정해주시면 참석자들께서 더 잘 따라오실 것 같습니다. (자유롭게 두시면 이 후 동작부분에서 이미지 이름을 기억 못하시는 분이 있을 수도 있습니다. ㅎㅎ)

또 Docker ps -a를 통해서 정지되어 있는 컨테이너인 ubuntu:latest의 container_id를 찾는 부분을 추가해주시면 좋을 것 같습니다 ㅎㅎ

**Comment by sangyeol-kim** [comment]
exit 명령어는 명진이 도움으로 추가했습니다!

이미지 이름과 태그 부분은 5번 실습에서는 직접 이미지 명을 만들어서 빌드해보고 8번 실습에서 이미지명과 태그를 지정해서 실습을 진행하는 방향으로 수정했습니다.

docker ps -a <container_id>도 ps 명령어 아래에 자세하게 추가했습니다.

미처 신경쓰지 못한 부분이 많았는데 감사합니다 :)
