### ISSUE TITLE
11번 수정사항

### ISSUE THREAD

**Issue by yebonkim** [sangyeol-kim/ausg-docker-seminar#7]
저는 subicura/jenkins:02 이미지 파일이 없어 오류가 났었습니다. ㅎㅎ

docker pull subicura/jenkins:2

명령어 추가를 통해 이미지를 먼저 다운받도록 추가해주시면 좋을 것 같습니다. 해당 이미지 이름이 'subicura/jenkins:2' 이기때문에 

명령어의 이미지 이름역시 subicura/jenkins:02 -> subicura/jenkins:2로 변경되어야 할 것 같습니다.

그리고 저는 '$(데이터 저장될 디렉토리): ' 부분에서 콜론이 있으면 수강하시는 분들이 혼동하실 것 같습니다...!

**Comment by sangyeol-kim** [comment]
수정했습니다 :)
